CLASS zcl_abap_koans_about_abapunit DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_abap_koans_about_abapunit IMPLEMENTATION.
ENDCLASS.
